### ISSUE TITLE
トップ画面にDBのアラーム設定表示機能を追加

### ISSUE THREAD

**Issue by nsaito92** [nsaito92/Frock#14]
# 概要 #

* TOP画面にて、DBのデータを元に現在のアラーム設定の一覧を表示できる様にする

# 期待値 #

1. 【done】トップ画面から、DBのアラーム設定編集機能作成
1. 【done】トップから項目長押しで、削除機能削除を追加
1. 【done】アラーム設定の新規作成機能を追加
1. 【done】アラーム設定新規作成のバリデーション機能を追加
1. 【done】DB保存時、ホーム画面に戻る処理を追加。
1. 【done】SQLエラーの修正

# 対応内容 #
#### 構成の概要
* Database
    * queryとcursorを使ってデータを取得
* ArrayList
    * DBから取得したデータを、入れる。
* Adapter(BaseAdapter)
    * レイアウトを決めて、ListViewに渡す。
* ListView
    * 渡されたArraylistを元に、Viewに反映する。

#### 実装概要

* レイアウト
    * 以下のレイアウト用xmlを作成。
    * 画面全体のxml
    * 項目ごとの1行単位のxml
* 実装
    * Adapterクラス
        * `BaseAdapter`を継承したAdapterクラスを作成する。
        * リスト項目一つ一つに対して呼ばれる`getView`にて、DBのデータ取得+View表示様に文字整形を行う様にする。
    * Activity
        * 画面表示処理
        * DBを読み込み処理
            * DBからデータを取得して、アイテムリストのオブジェクトに　addしていく。フィールドのListViewに内容を表示する。

#### 対応順

1. Adapterクラスを新規作成
1. DB読み込み処理を追加
1. アダプタを使用して、getView時の処理
1. DBのデータをビューに表示する際の整形処理

#### 参考情報

* [Android：ListViewとAdapter、そしてSQLiteを使う](https://asky.hatenablog.com/entry/2016/05/08/013038)のサンプルがわかりやすそう。
* [Android ListViewとAdapterとViewHolder](https://kamiya-kizuku.hatenablog.com/entry/2017/12/26/201623)も。

# 参考情報

* 

# 備考 #

*

**Comment by nsaito92** [comment]
### Androidのリスト表示について調査

#### 関連機能

* 以下でリスト表示に対応する。
* **ListView**
    * 縦にスクロールする一覧表示のための View。
    * ListView自体に、一覧の中身を管理する機能は無い。
    * Adapter という仕組みを用いて、データソースの管理と、データのViewへのバインドをさせる。
    * ListView は、スクロール位置に合わせて必要な View を Adapter から取り出す。
* **BaseAdapter**
    * Adapterの複数ある種類のうちの一つ。

#### 備考

* 使用しようとしたが、ボツにしたもの。
    * ~~**SimpleCursorAdapter**~~
        * Adapterの複数ある種類のうちの一つ。
        * データベースへ問い合わせた結果を View へ容易にバインドできるようにしたCursorAdapter。
        * 資料が少なく、ListViewに反映する際に、データを整形してからViewに表示する方法の調査に時間がかかりそうだったので、別の方法を使用する。

#### 参考ページ

* [mixi-inc.github.io/AndroidTraining](http://mixi-inc.github.io/AndroidTraining/fundamentals/2.06.listView-and-viewPager.html)
* [sqliteで取得した値をListViewに表示する簡単な例
](https://qiita.com/zaburo/items/b02f439e3f2c5ddb1c58#helper)

**Comment by nsaito92** [comment]
以下も修正する。

```
05-09 02:08:27.577 25506-25515/org.bitbucket.snaoto22.frock W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/org.bitbucket.snaoto22.frock/databases/AppSettingsDB.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
```

**Comment by nsaito92** [comment]
```
05-20 00:41:23.126 3446-3446/org.bitbucket.snaoto22.frock E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: org.bitbucket.snaoto22.frock, PID: 3446
                                                                            java.lang.RuntimeException: Unable to start activity ComponentInfo{org.bitbucket.snaoto22.frock/com.example.naotosaito.clocktest.AlarmPreferenceActivity}: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2711)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2772)
                                                                                at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1515)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:241)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6223)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                             Caused by: android.database.CursorIndexOutOfBoundsException: Index 0 requested, with a size of 0
                                                                                at android.database.AbstractCursor.checkPosition(AbstractCursor.java:460)
                                                                                at android.database.AbstractWindowedCursor.checkPosition(AbstractWindowedCursor.java:136)
                                                                                at android.database.AbstractWindowedCursor.getInt(AbstractWindowedCursor.java:68)
                                                                                at com.example.naotosaito.clocktest.FrockSettingsHelperController.getAlarmSettingEntity(FrockSettingsHelperController.java:164)
                                                                                at com.example.naotosaito.clocktest.AlarmPreferenceActivity.onCreate(AlarmPreferenceActivity.java:67)
                                                                                at android.app.Activity.performCreate(Activity.java:6705)
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2664)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2772) 
                                                                                at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1515) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                at android.os.Looper.loop(Looper.java:241) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6223) 
                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
05-20 00:41:28.923 3446-3467/org.bitbucket.snaoto22.frock W/SQLiteConnectionPool: A SQLiteConnection object for database '/data/user/0/org.bitbucket.snaoto22.frock/databases/AppSettingsDB.db' was leaked!  Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.

```

DBからデータを削除したので、列が削除されている。
アダプタのポジションと状態が一致していないため、データが無しとなりクラッシュしている。

```
sqlite> select _id, status, hour, minute, week from alarmsettingsdb;
1|1|0|20|3,4,5,6
3|1|0|15|0,1,2
4|1|0|22|
5|1|0|0|
sqlite> 
```

**Comment by nsaito92** [comment]
### リスト表示の項目が選択された際の処理 対応メモ

#### シーケンスメモ

1. ユーザーに選択された項目の検知
1. 選択していた項目のデータをIntentのパラメーターとしてセット
1. アラーム設定画面へのIntent発行
1. 渡された情報を元に、アラーム設定画面を表示。

#### 備考

* 参考ページ
    * [[Android] ListView リストをタップして画面遷移させてみる
](https://akira-watson.com/android/listview_2.html)

**Comment by nsaito92** [comment]
### バリデーション対応 対応メモ

#### 対応方針

* アラーム設定は、10件まで。
* 10件を超えた場合は、新規追加できない様にする。

#### 対応方法

* 10件の判定方法
    * アラーム新規設定画面を開く先に、DBのデータ数をチェック。
    * 10件入っていた場合は、遷移させない様にする。

#### 備考

* 参考情報
    * [指定したカラムまたはテーブル全体の行数をカウント(count関数)](https://www.dbonline.jp/sqlite/function/index1.html)
    * [【Android】テーブルのレコード数を簡単に取得する](https://qiita.com/operandoOS/items/eb829a56f28d2c56a436)

**Comment by nsaito92** [comment]
対応完了、これ以降は障害チケットで対応。
