### ISSUE TITLE
DBのデータを元にアラームが鳴動する機能を追加する

### ISSUE THREAD

**Issue by nsaito92** [nsaito92/Frock#16]
# 概要 #
* #14 でアラーム設定をDBに保存出来る様に対応した。
* こちらのデータを元に、アラームが鳴動する機能を追加する。

# 期待値 #

* アラームが動作する様になること。

# 対応内容 #

* https://github.com/nsaito92/Frock/issues/16#issuecomment-653563905 を参照。

# 参考情報

* 

# 備考 #

*

**Comment by nsaito92** [comment]
## チケット内対応内容の全体像

* 要件整理
* 詳細設計
* 技術調査
* 実装

## 要件整理

実現したいこと

* DBに保存されているアラーム設定を元に、該当時間になったらアラームを実行できる様にする。

## 基本設計

* 複数有効なアラーム設定が存在している場合でも、それぞれ実行される様にする。
    * 例 : アラーム設定1(10:00に鳴動) → アラーム設定2(10:05に鳴動)
    * 止められていなかった場合どうする?
        * 鳴動中のアラームが止められた後、控えていたアラーム鳴動、とさせたい。
        * とはいえ、待機時間の区切りをどこかでつけたい。
    * 完全に時間がかぶった場合はどうする?
        * requestCodeが若い順番に鳴動させたい
        * とはいえ、待機時間の区切りをどこかでつけたい。

## 詳細設計

### 機能一覧

* DBデータを元にアラームサービスを生成する機能
* 生成されたアラームサービスの機能
* アラームサービスの終了する機能

#### DBデータを元にアラームサービスを生成する機能

* 以下の処理を行い、アラーム鳴動サービスを生成する。
    1. DBのデータ更新を検知。
        1. 新規作成 or 更新だった場合、アラーム設定`status`の状態をチェックする。
            1. 「ON」だった場合
                1. 該当positionのDBデータを取得し、該当の時間にアラームサービスを立ち上げるPendingIntentを生成。
                    * ※PendingIntentが生成済みだった場合は、PendingIntentを上書きで更新。(`FLAG_CANCEL_CURRENT`)
            2. 「OFF」だった場合
                1. PendingIntentが生成済みだった場合は、削除する。(`Pendingintent.cancel()`)
        1. 削除だった場合、アラーム設定`status`の状態をチェックする。
            1. 「ON」だった場合
                1. PendingIntentが生成されているはずなので、アラーム予定を取り消す。(`pendingintent.cancel()`)
            2. 「OFF」だった場合
                1. 何も行わない。
            * ※TODO ここN/OFFで処理分ける必要無いかも
    1. 処理終了。

#### 生成されたアラームサービスの機能

* アラーム開始時間になったら、以下の処理を行う。
    1. ローカルの音楽ファイルを読み込み、再生開始
    1. アラーム鳴動通知ダイアログを表示

#### アラームサービスの終了する機能

1. サービスの終了依頼がきた時に、以下の処理を行う。
    1. 音楽の終了

### DBデータの扱いについて
* DBに保存されているデータは、以下の様に扱う。
    * `_id`
        * ~~使用予定無し。~~ → RequestCodeの値に使用する。
    * `status`
        * **ONの場合のみ、アラームサービスが設定される様にする。**
        * OFFの場合は、いくら更新されようがサービスは実行されない。
    * `hour`
        * `minute`と組み合わせて、アラームが鳴動する **「時間」** の判断に使用する。
    * `minute`
        * `hour`と組み合わせて、アラームが鳴動する **「時間」** の判断に使用する。
    * `week`
        * アラームが鳴動する **「日にち(xx年xx月xx日)」** の判断に使用する。

## 技術調査

### PendingIntentのRequestCodeについて

* [PendingIntentとAlermManager](http://mashi.exciton.jp/archives/tag/pendingintent)
    * こちらの内容を元に、「DBデータを元にアラームサービスを生成する機能」の項目を検討。

**Comment by nsaito92** [comment]
次の作業
* PendingIntentの生成の仕様検討
* 紙に書いた方がいいかも

**Comment by nsaito92** [comment]
以下のエラーが発生。

```
06-15 16:46:27.249 11253-11253/org.bitbucket.snaoto22.frock E/AndroidRuntime: FATAL EXCEPTION: main
                                                                              Process: org.bitbucket.snaoto22.frock, PID: 11253
                                                                              java.lang.RuntimeException: Unable to stop service com.example.naotosaito.clocktest.AlarmService@9842dc: java.lang.NumberFormatException: null
                                                                                  at android.app.ActivityThread.handleStopService(ActivityThread.java:3418)
                                                                                  at android.app.ActivityThread.-wrap27(ActivityThread.java)
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1625)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                  at android.os.Looper.loop(Looper.java:241)
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6223)
                                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                               Caused by: java.lang.NumberFormatException: null
                                                                                  at java.lang.Integer.parseInt(Integer.java:483)
                                                                                  at java.lang.Integer.parseInt(Integer.java:556)
                                                                                  at com.example.naotosaito.clocktest.AlarmService.onDestroy(AlarmService.java:80)
                                                                                  at android.app.ActivityThread.handleStopService(ActivityThread.java:3401)
                                                                                  at android.app.ActivityThread.-wrap27(ActivityThread.java) 
                                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1625) 
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                  at android.os.Looper.loop(Looper.java:241) 
                                                                                  at android.app.ActivityThread.main(ActivityThread.java:6223) 
                                                                                  at java.lang.reflect.Method.invoke(Native Method) 
                                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
```

* 原因
    * `onDestroy()` 呼び出し時、requestcodeがnullになっていたため型変換が出来ていなかったため。
* 修正方法
    * サービス上ではなく、アラーム鳴動中画面の停止ボタンがタップされた際に、際設定処理を行う様に修正。
* 備考
    * 以下のページを参考にした。
        * [【初心者向け】よく出会うJavaのエラーと対策7選！](https://eng-entrance.com/java-basic-error)

**Comment by nsaito92** [comment]
端末再起動パターンが考慮出来ていなさそう。

**Comment by nsaito92** [comment]
### アラーム起動予定の重複について検討

* 現状だと、DBの設定ごとにAlarmManagerにセットするが、時間が重複した場合、AlarmServiceが同時に起動してしまう。
* 時間が重複している場合、起動するアラームは一つだけとしたいため、Alarmmanagerに現在設定されているアラームを取得する仕様としたいが、AlarmManagerにセット済みの設定を取得する処理は存在していない模様。
* 参考に端末に入っていたソニーの時計アプリのアラーム設定を確認したところ、Alarmmanagerにセットするアラーム設定は常に一つだけである模様。
* 上記の仕様を参考にする方が処理は簡潔になるかもしれない・・

#### ソニーの時計アプリのアラーム設定について確認。

ONになっているアラーム設定が二つある状態で、内部データを確認。

---

アラーム設定一覧を取得。
```
$ adb shell dumpsys alarm | grep com.sonyericsson.organizer
```

一番近いアラーム設定のみ、AlarmManagerにセットされている模様。
```
1592778600000 : Your time zone: 2020年6月22日 月曜日 07:30:00 GMT+09:00
```
上記のアラーム設定をOFFにして、サイドアラーム取得コマンドを実行。
次に近いアラーム設定が一つだけ設定される様になった。
```
1592782200000 : Your time zone: 2020年6月22日 月曜日 08:30:00 GMT+09:00
```

**Comment by nsaito92** [comment]
03cea083c6b4b81188e217542203f23b74a68103 対応後の単体テストログ。

```

06-30 23:29:50.420 21210-21210/org.bitbucket.snaoto22.frock D/AlarmServiceSetter: UpdateAlarmService
06-30 23:29:50.420 21210-21210/org.bitbucket.snaoto22.frock D/FrockSettingsOpenHelper: FrockSettingsOpenHelper
06-30 23:29:50.420 21210-21210/org.bitbucket.snaoto22.frock D/FrockSettingsHelperController: getValidCalender
06-30 23:29:50.421 21210-21210/org.bitbucket.snaoto22.frock D/FrockSettingsHelperController: getCursorForValidSettings
06-30 23:29:50.429 21210-21210/org.bitbucket.snaoto22.frock D/FrockSettingsHelperController: cursor.getCount() = 4
06-30 23:29:50.429 21210-21210/org.bitbucket.snaoto22.frock D/FrockSettingsHelperController: root 1st : 0
06-30 23:29:50.430 21210-21210/org.bitbucket.snaoto22.frock D/ClockUtil: convertStringToArray
06-30 23:29:50.430 21210-21210/org.bitbucket.snaoto22.frock D/FrockSettingsHelperController: root 2nd cnt2 = 0
06-30 23:29:50.430 21210-21210/org.bitbucket.snaoto22.frock D/FrockSettingsHelperController: root 2nd cnt2 = 1
06-30 23:29:50.431 21210-21210/org.bitbucket.snaoto22.frock D/FrockSettingsHelperController: root 2nd cnt2 = 2
06-30 23:29:50.431 21210-21210/org.bitbucket.snaoto22.frock D/FrockSettingsHelperController: root 2nd cnt2 = 3
06-30 23:29:50.432 21210-21210/org.bitbucket.snaoto22.frock D/FrockSettingsHelperController: root 2nd cnt2 = 4
06-30 23:29:50.432 21210-21210/org.bitbucket.snaoto22.frock D/FrockSettingsHelperController: root 2nd cnt2 = 5
06-30 23:29:50.433 21210-21210/org.bitbucket.snaoto22.frock D/FrockSettingsHelperController: root 2nd cnt2 = 6
06-30 23:29:50.456 21210-21210/org.bitbucket.snaoto22.frock D/FrockSettingsHelperController: alarmCld = Wed Jul 01 09:00:00 GMT+09:00 2020

06-30 23:29:50.456 21210-21210/org.bitbucket.snaoto22.frock D/FrockSettingsHelperController: root 1st : 1
06-30 23:29:50.456 21210-21210/org.bitbucket.snaoto22.frock D/ClockUtil: convertStringToArray
06-30 23:29:50.456 21210-21210/org.bitbucket.snaoto22.frock D/FrockSettingsHelperController: root 2nd cnt2 = 0
06-30 23:29:50.457 21210-21210/org.bitbucket.snaoto22.frock D/FrockSettingsHelperController: root 2nd cnt2 = 1
06-30 23:29:50.458 21210-21210/org.bitbucket.snaoto22.frock D/FrockSettingsHelperController: alarmCld = Fri Jul 03 06:00:00 GMT+09:00 2020

06-30 23:29:50.458 21210-21210/org.bitbucket.snaoto22.frock D/FrockSettingsHelperController: root 1st : 2
06-30 23:29:50.458 21210-21210/org.bitbucket.snaoto22.frock D/ClockUtil: convertStringToArray
06-30 23:29:50.458 21210-21210/org.bitbucket.snaoto22.frock D/FrockSettingsHelperController: root 2nd cnt2 = 0
06-30 23:29:50.459 21210-21210/org.bitbucket.snaoto22.frock D/FrockSettingsHelperController: alarmCld = Wed Jul 01 23:22:00 GMT+09:00 2020

06-30 23:29:50.459 21210-21210/org.bitbucket.snaoto22.frock D/FrockSettingsHelperController: root 1st : 3
06-30 23:29:50.459 21210-21210/org.bitbucket.snaoto22.frock D/ClockUtil: convertStringToArray
06-30 23:29:50.459 21210-21210/org.bitbucket.snaoto22.frock D/FrockSettingsHelperController: root 2nd cnt2 = 0
06-30 23:29:50.460 21210-21210/org.bitbucket.snaoto22.frock D/FrockSettingsHelperController: root 2nd cnt2 = 1
06-30 23:29:50.460 21210-21210/org.bitbucket.snaoto22.frock D/FrockSettingsHelperController: root 2nd cnt2 = 2
06-30 23:29:50.461 21210-21210/org.bitbucket.snaoto22.frock D/FrockSettingsHelperController: alarmCld = Wed Jul 01 08:05:00 GMT+09:00 2020

06-30 23:29:50.461 21210-21210/org.bitbucket.snaoto22.frock D/ClockUtil: isClosestCalender
06-30 23:29:50.463 21210-21210/org.bitbucket.snaoto22.frock D/AlarmServiceSetter: closestcalender = Wed Jul 01 08:05:00 GMT+09:00 2020

```

**Comment by nsaito92** [comment]
アラームをちゃんと停止できているか、もう一度確認したらこのチケットは完了?

**Comment by nsaito92** [comment]
再起動後、アラーム設定の再設定が出来ていない。

---
再起動前
```
SCV46:/ $ dumpsys alarm | grep org.bitbucket.snaoto22.frock                                                                    
    RTC #3: Alarm{a5ea388 type 1 when 1593568800220 org.bitbucket.snaoto22.frock}
      tag=*alarm*:org.bitbucket.snaoto22.frock/com.example.naotosaito.clocktest.AlarmService
      operation=PendingIntent{34f4121: PendingIntentRecord{e94a0dc org.bitbucket.snaoto22.frock startService}}
   (AppSync) org.bitbucket.snaoto22.frock/0
```

再起動後
```
SCV46:/ $ dumpsys alarm | grep org.bitbucket.snaoto22.frock                                                                    
   (AppSync) org.bitbucket.snaoto22.frock/0
```

**Comment by nsaito92** [comment]
https://github.com/nsaito92/Frock/issues/16#issuecomment-640184290 にて検討した内容からの、
最終的な対応内容について記載する。

## 基本設計

* 複数有効なアラーム設定が存在している場合でも、それぞれ実行される様にする。
    * 例 : アラーム設定1(10:00に鳴動) → アラーム設定2(10:05に鳴動)
    * 鳴動中に、次のアラームの実行時間がきた場合の挙動
        * 現在鳴動していたアラームが終了し、次のアラームが鳴動する。
    * 同じ時間のアラーム設定が複数存在していた場合、どちらが優先されるか
        * 先に作成されていたアラーム設定を優先する。

## 詳細設計

### 機能一覧

* アラーム設定管理クラス
    * アラームサービス更新処理
        * アラームサービス設定処理
            * DBデータを元にアラームサービスを生成する機能
        * アラームサービス終了処理
* 生成されたアラームサービスの機能

#### DBデータを元にアラームサービスを生成する機能

* 以下の処理を行い、アラーム鳴動サービスを生成する。
    1. DBのデータ更新を検知。
        1. 新規作成 or 更新だった場合、アラーム設定`status`の状態をチェックする。
            1. 「ON」だった場合
                1. 該当positionのDBデータを取得し、該当の時間にアラームサービスを立ち上げるPendingIntentを生成。
                    * ※PendingIntentが生成済みだった場合は、PendingIntentを上書きで更新。(`FLAG_CANCEL_CURRENT`)
            2. 「OFF」だった場合
                1. PendingIntentが生成済みだった場合は、削除する。(`Pendingintent.cancel()`)
        1. 削除だった場合、アラーム設定`status`の状態をチェックする。
            1. 「ON」だった場合
                1. PendingIntentが生成されているはずなので、アラーム予定を取り消す。(`pendingintent.cancel()`)
            2. 「OFF」だった場合
                1. 何も行わない。
            * ※TODO ここN/OFFで処理分ける必要無いかも
    1. 処理終了。

#### 生成されたアラームサービスの機能

* アラーム開始時間になったら、以下の処理を行う。
    1. ローカルの音楽ファイルを読み込み、再生開始
    1. アラーム鳴動通知ダイアログを表示

#### アラームサービスの終了する機能

1. サービスの終了依頼がきた時に、以下の処理を行う。
    1. 音楽の終了

### データ設計
### 新規データ
* 特に新規で永続化するデータは無し。

#### 既存データ(DB)の使い方について
* DBに保存されているデータは、以下の様に扱う。
    * `status`
        * **ONの場合のみ、アラームサービスが設定される様にする。**
        * OFFの場合は、いくら更新されようがサービスは実行されない。
    * `hour`
        * `minute`と組み合わせて、アラームが鳴動する **「時間」** の判断に使用する。
    * `minute`
        * `hour`と組み合わせて、アラームが鳴動する **「時間」** の判断に使用する。
    * `week`
        * アラームが鳴動する **「日にち(xx年xx月xx日)」** の判断に使用する。

## 技術調査

### PendingIntentのRequestCodeについて

* [PendingIntentとAlermManager](http://mashi.exciton.jp/archives/tag/pendingintent)
    * こちらの内容を元に、「DBデータを元にアラームサービスを生成する機能」の項目を検討。

## 実装

*

**Comment by nsaito92** [comment]
マージ完了。
