### ISSUE TITLE
スヌーズ機能障害対応

### ISSUE THREAD

**Issue by nsaito92** [nsaito92/Frock#27]
# 概要 #

* 

# 期待値 #

* 

# 対応内容 #

* 

# 参考情報

* 

# 備考 #

*

**Comment by nsaito92** [comment]
## エラー対応
* アラーム設定の時間が狂う(スヌーズカウントのリセットが漏れている)
* 通知が消えない
* アラーム禁止ダイアログ表示時、メモリリークエラー発生

### 画面起動時のメモリリークエラーについて
#### 調査結果

* [こちらと、ページ内のリンクの参考ページを参照。](http://blog.livedoor.jp/sen_ritsu/archives/51274118.html)
    * Activity終了中に、Dialog#showを呼んだため、と記載されている。
* CallAlarmDialogActivityでfinishをする場合は、createをしたdialogの`dialog#dismiss()`を呼ぶ必要があった。

#### 調査メモ

* リークのログの発生前、`CallAlarmDialogActivity`の onDestroyが呼ばれている。
* 記事と同じ状態に見える。

```
08-09 17:29:42.285 3257-3257/org.bitbucket.snaoto22.frock D/CallAlarmDialogActivity: onDestroy
08-09 17:29:42.287 3257-3257/org.bitbucket.snaoto22.frock D/ViewRootImpl@40f4ddf[CallAlarmDialogActivity]: dispatchDetachedFromWindow
08-09 17:29:42.288 4153-17319/? V/WindowManager: Remove Window{24aa347 u0 org.bitbucket.snaoto22.frock/com.example.naotosaito.clocktest.CallAlarmDialogActivity EXITING}: mSurfaceController=Surface(name=org.bitbucket.snaoto22.frock/com.example.naotosaito.clocktest.CallAlarmDialogActivity[3257])/@0xd172b2f mAnimatingExit=true mRemoveOnExit=false mHasSurface=true surfaceShowing=true isAnimationSet=true app-animation=true mWillReplaceWindow=false inPendingTransaction=false mDisplayFrozen=false callers=com.android.server.wm.WindowState.removeIfPossible:2800 com.android.server.wm.WindowManagerService.removeWindow:1963 com.android.server.wm.Session.remove:274 android.view.IWindowSession$Stub.onTransact:347 com.android.server.wm.Session.onTransact:192 android.os.Binder.execTransact:739 
08-09 17:29:42.288 27256-27733/? E/SVAudioRendererNative: SVBufferManager::peekNextBufferToBeConsumed() ERROR illegal state: 0
08-09 17:29:42.289 27256-27733/? I/chatty: uid=10202(com.apple.android.music) ExoPlayerImplIn identical 1 line
08-09 17:29:42.289 27256-27733/? E/SVAudioRendererNative: SVBufferManager::peekNextBufferToBeConsumed() ERROR illegal state: 0
08-09 17:29:42.293 4153-17319/? D/InputTransport: Input channel destroyed: fd=510
08-09 17:29:42.293 3257-3257/org.bitbucket.snaoto22.frock D/InputTransport: Input channel destroyed: fd=95

```


```
08-09 17:29:42.297 3257-3257/org.bitbucket.snaoto22.frock E/WindowManager: android.view.WindowLeaked: Activity com.example.naotosaito.clocktest.CallAlarmDialogActivity has leaked window DecorView@1d31bce[CallAlarmDialogActivity] that was originally added here
                                                                               at android.view.ViewRootImpl.<init>(ViewRootImpl.java:729)
                                                                               at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:365)
                                                                               at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
                                                                               at android.app.Dialog.show(Dialog.java:470)
                                                                               at com.example.naotosaito.clocktest.CallAlarmDialogActivity.onCreate(CallAlarmDialogActivity.java:72)
                                                                               at android.app.Activity.performCreate(Activity.java:7353)
                                                                               at android.app.Activity.performCreate(Activity.java:7344)
                                                                               at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1275)
                                                                               at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3142)
                                                                               at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3305)
                                                                               at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
                                                                               at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
                                                                               at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
                                                                               at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1993)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                               at android.os.Looper.loop(Looper.java:216)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:7285)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

```

* ダイアログ画面のonDestoryは、Activityクラス内部のfinish処理で呼ばれているものと思われる。
* Activity#onCreate → Activity#finish → Activity#onDestoryというフローが発生しているため、発生しているエラーの可能性が高い。
* finishを呼んでいる箇所を調査。
    * BroadcastReceiver#onReceive
        * アラーム鳴動終了イベント受信用receiverで、アラーム鳴動開始から一定時間後、ダイアログ画面を終了する時に呼ばれる。
        * ダイアログ起動時に呼ばれる処理では無いため、問題なし。
    * ダイアログ画面で、「停止」ボタンを押した時
    * ダイアログ画面で、「後で」ボタンを押した時
    * onResume
        * アラームサービスが動いてなければfinish

```    

08-09 17:29:31.884 3257-6579/org.bitbucket.snaoto22.frock D/AlarmServiceObserver: onHandleIntent // アラーム鳴動中

08-09 17:29:32.077 3257-3257/org.bitbucket.snaoto22.frock D/CallAlarmDialogActivity: onCreate // 鳴動中なので、アラームサービスから画面生成

08-09 17:29:32.179 3257-3257/org.bitbucket.snaoto22.frock D/CallAlarmDialogActivity: onResume // 画面生成完了

08-09 17:29:41.892 3257-3257/org.bitbucket.snaoto22.frock D/AlarmService: onDestroy // アラーム鳴動時間終了。この後終了イベントを投げる。

08-09 17:29:41.958 3257-6579/org.bitbucket.snaoto22.frock D/AlarmServiceSetter: updateAlarmService // 次のアラーム時間の更新

08-09 17:29:41.981 3257-3257/org.bitbucket.snaoto22.frock D/CallAlarmDialogActivity: receiver // イベントを受け取った。画面を終了する。

08-09 17:29:42.285 3257-3257/org.bitbucket.snaoto22.frock D/CallAlarmDialogActivity: onDestroy // 画面終了。

08-09 17:29:42.297 3257-3257/org.bitbucket.snaoto22.frock E/WindowManager: android.view.WindowLeaked: Activity com.example.naotosaito.clocktest.CallAlarmDialogActivity has leaked window DecorView@1d31bce[CallAlarmDialogActivity] that was originally added here

```
