### ISSUE TITLE
アラームONかつ、曜日設定が「無し」の状態で設定保存するとクラッシュする。

### ISSUE THREAD

**Issue by nsaito92** [nsaito92/Frock#41]
# 概要 #

* アラームONかつ、曜日設定が「無し」のパターンが考慮出来ていないっぽい。

```
12-06 16:32:03.899 30521-30521/com.github.nsaito92.Frock E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: com.github.nsaito92.Frock, PID: 30521
                                                                           java.lang.NullPointerException: Attempt to get length of null array
                                                                               at com.example.naotosaito.clocktest.FrockSettingsHelperController.getClosestCalender(FrockSettingsHelperController.java:474)
                                                                               at com.example.naotosaito.clocktest.AlarmServiceSetter.getAlarmSetCalender(AlarmServiceSetter.java:87)
                                                                               at com.example.naotosaito.clocktest.AlarmServiceSetter.updateAlarmService(AlarmServiceSetter.java:30)
                                                                               at com.example.naotosaito.clocktest.AlarmPreferenceActivity$5.onPreferenceClick(AlarmPreferenceActivity.java:278)
                                                                               at android.preference.Preference.performClick(Preference.java:1250)
                                                                               at android.preference.PreferenceScreen.onItemClick(PreferenceScreen.java:262)
                                                                               at android.widget.AdapterView.performItemClick(AdapterView.java:362)
                                                                               at android.widget.AbsListView.performItemClick(AbsListView.java:1689)
                                                                               at android.widget.AbsListView$PerformClick.run(AbsListView.java:4130)
                                                                               at android.widget.AbsListView$7.run(AbsListView.java:6594)
                                                                               at android.os.Handler.handleCallback(Handler.java:873)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                               at android.os.Looper.loop(Looper.java:216)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:7285)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)

```

# 期待値 #

* 

# 対応内容 #

* 

# 参考情報

* 

# 備考 #

*

**Comment by nsaito92** [comment]
### 原因
* アラーム設定が保存されると、次に最短のアラーム予定を確認する。
* その際に、アラームが「ON」になっている設定がチェック対象になるが、現状「ONになっているが曜日が選択されていない」設定も対象となっている。
* 次の鳴動予定の判断には、Calenderの生成が必要となるが、それには曜日設定が必要となるため、参照するデータが存在せず、エラーとなっている。

### 対応方法
1. 曜日設定がなかった設定は、次の最短アラーム確認処理の対象からアラーム設定から除外する。
    * メリット
        * 曜日を入力せずとも、設定をとりあえず作成出来る。
    * デメリット
        * ONになっているのに、アラームが設定されないように見える。
        * ユーザーにアラームが実は有効になっていないことが伝わりづらい。
        * DB処理に影響が出るため、影響範囲はそれなりになる。
1. アラーム設定保存時に曜日設定が未入力の場合は、バリデーションエラーで保存できないようにする。
    * メリット
        * DBに保存する段階で除外できるため、既存の最短アラーム設定処理に影響が出ない。
        * バリデーションエラー対応だけなので、対応はそこまで重くはない。
    * デメリット
        * エラーを出すため、ユーザーにも設定が必要なことが伝わる。
1. 曜日設定がないアラーム設定は、「最短の曜日」の時間を対象としている仕様とする。
    * メリット
        * プリインされている時計アプリの動作に近い。
    * デメリット
        * 思いつきなので、仕様検討がもう少し必要になる。
        * 微妙に複雑な気もするので、おそらく一番対応は重い。

### 対応方針

2での対応とする。

**Comment by nsaito92** [comment]
//IDは、ユーザーが入力するものではないので、チェック不要。
            // アラーム ON/OFFは、ユーザーは0か1以外入力する方法はないためチェック不要。
            // 時は、初期値で「00」が入力される仕様としているため、チェック不要。
            // 分は、初期値で「00」が入力される仕様としているため、チェック不要。

            // 曜日は何も入力されない場合があるため、チェック。

            //音楽ファイルのURIは選択されていない可能性があるが、その場合内包している音楽ファイルを使用する使用になっているため、チェック不要。

**Comment by nsaito92** [comment]
アラーム設定保存時の永続的なURI許可設定処理時のURIのnullチェックも漏れていたため、上記コミットで合わせて修正している。
