### ISSUE TITLE
アラーム設定のDB化対応

### ISSUE THREAD

**Issue by nsaito92** [nsaito92/Frock#7]
# 概要 #

* アラーム設定を、DBで管理し、複数のアラーム設定をアプリ内で保存できる様にする。
* 設定の追加、削除、編集ができるところまで検討する。
* 今後、マイグレが発生することを考慮する。
* 今後、保存する機能が増えても問題ないことを考慮する。
* 保存できるアラーム設定数を決める。

# 期待値 #

* 

# 対応内容 #

* 

# 参考情報

* 

# 備考 #

*

**Comment by nsaito92** [comment]
# アラーム設定のDB化対応やること

1.  技術調査
	* AndroidにおけるDB対応方法を調査。
	* 調査結果をもって、要件を満たす見込みがあるか確認。
1.  仮実装
	* 調査結果を持って仮実装。
	* 想定していた通りの挙動となるか確認。
1. 仕様検討
	* 仮実装の結果をもって仕様の整理。
	* 細かい仕様検討を行う。
		* マイグレ
		* 性能要件
1. 本実装
	* 仕様を検討した結果を持って、最終的なコード調整。

**Comment by nsaito92** [comment]
# DB構成検討

## SQLiteOpenHelperを使用する

### 例

* [こちらを例に検討。](https://qiita.com/kengo_kuwahara/items/a8ef858a9810cad42ca6)
	* DATABASE_NAME = "TestDB.db";
	* TABLE_NAME = "testdb";
	* _ID = "_id";
	* COLUMN_NAME_TITLE = "title";
	* COLUMN_NAME_SUBTITLE = "score";

### table「testdb」

以下の様な状態になっている。

|---| title | score |
|---|---|---|
|| music1 |10|
|| music2 |0|
|| music3 |0|

### DB対応案

* 以下の様な、table「alarmsettingsdb」を作成する。

|---| on/off | time | week | sound |
|---|---|---|---|---|
|| on |21:00|月火水木金|ファイル1|
|| off |09:00|土、日|ファイル3|
|| on |08:00|水|ファイル5|

### 見解

* 上記の様な構成で対応可能だと思われる。

### 懸念点

* .dbファイルを今後どこまで使用するか？
	* アラーム設定以外で使用したくなった際に、今回作成したDBにtableを追加する形にする？
* 今回DBの内部データを表示、編集する画面の仕様をどうするか？

**Comment by nsaito92** [comment]
SQLiteOpenHelperの実装中。暫定デバッグ版として画面にDB内部の情報を出力する機能を追加する。

**Comment by nsaito92** [comment]
とりあえず、DBの状態を確認するだけなら、adbでも出来る。

https://qiita.com/tesoro/items/d3e697bff8720db03b20

**Comment by nsaito92** [comment]
> * 試験的にDB周り実装したところ、エラー

SQL文の半角スペース文ミスだった。

**Comment by nsaito92** [comment]
> > * 試験的にDB周り実装したところ、エラー
> 
> SQL文の半角スペース文ミスだった。
> 上記のエクセプションの場合は、SQL文法を見直すのが早そう。

上記は解決したが、別の問題。

```
01-06 00:13:47.563 9904-9904/org.bitbucket.snaoto22.frock D/FrockSettingsOpenHelper: onCreate
01-06 00:13:47.564 9904-9904/org.bitbucket.snaoto22.frock D/FrockSettingsOpenHelper: SQL_CREATE_ENTRIES = CREATE TABLE alarmsettingsdb (_id INTEGER PRIMARY KEY,status INTEGER,hour INTEGER,minute INTEGER,week TEXT)
01-06 00:13:47.564 9904-9904/org.bitbucket.snaoto22.frock D/FrockSettingsOpenHelper: saveData
01-06 00:13:47.565 9904-9904/org.bitbucket.snaoto22.frock D/FrockSettingsOpenHelper: saveData
01-06 00:13:47.565 9904-9904/org.bitbucket.snaoto22.frock E/SQLiteLog: (1) near "FROM": syntax error
01-06 00:13:47.569 9904-9904/org.bitbucket.snaoto22.frock D/AndroidRuntime: Shutting down VM
01-06 00:13:47.570 9904-9904/org.bitbucket.snaoto22.frock E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: org.bitbucket.snaoto22.frock, PID: 9904
                                                                            java.lang.RuntimeException: Unable to start activity ComponentInfo{org.bitbucket.snaoto22.frock/com.example.naotosaito.clocktest.MainActivity}: android.database.sqlite.SQLiteException: near "FROM": syntax error (code 1): , while compiling: SELECT FROM alarmsettingsdb
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2711)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2772)
                                                                                at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1515)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:241)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6223)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
                                                                             Caused by: android.database.sqlite.SQLiteException: near "FROM": syntax error (code 1): , while compiling: SELECT FROM alarmsettingsdb
                                                                                at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
                                                                                at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:895)
                                                                                at android.database.sqlite.SQLiteConnection.prepare(SQLiteConnection.java:506)
                                                                                at android.database.sqlite.SQLiteSession.prepare(SQLiteSession.java:588)
                                                                                at android.database.sqlite.SQLiteProgram.<init>(SQLiteProgram.java:58)
                                                                                at android.database.sqlite.SQLiteStatement.<init>(SQLiteStatement.java:31)
                                                                                at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1675)
                                                                                at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1606)
                                                                                at com.example.naotosaito.clocktest.FrockSettingsOpenHelper.onCreate(FrockSettingsOpenHelper.java:58)
                                                                                at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:251)
                                                                                at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:187)
                                                                                at com.example.naotosaito.clocktest.MainActivity.onCreate(MainActivity.java:32)
                                                                                at android.app.Activity.performCreate(Activity.java:6705)
                                                                                at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2664)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2772) 
                                                                                at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1515) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                at android.os.Looper.loop(Looper.java:241) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6223) 
                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755) 
01-06 00:13:47.571
```

**Comment by nsaito92** [comment]
とりあえずtableは出来たので、試験データを入れた。

```
sqlite> .table
alarmsettingsdb   android_metadata
sqlite> select _id, status, hour, minute, week from alarmsettingsdb;
_id|status|hour|minute|week
1|1|21|0|0,1
2|0|11|45|2,4
3|0|12|0|0,1
sqlite> 

```

**Comment by nsaito92** [comment]
### 経過メモ

DBのテストデータを元に、アラーム設定に投げ込む実装を検討中。

**Comment by nsaito92** [comment]
経過メモ
以下の検討を引き続き行う。
1. カラム「status」のデータによる、アラームON/OFF切り替え機能の検討
1. DBからアラーム設定したが、アラームが鳴動していない件の調査
1. DBの追加、編集、削除の検討

**Comment by nsaito92** [comment]
### アラーム設定編集画面の仕様について検討

#### 課題点

* 現在、アラーム設定編集画面は、DBの情報を読み取る実装がされていないため、DBに複数データがあっても、それをアプリ上で使用することが出来ない。

#### 調査すること

* DBのアラーム設定を読み取りアプリ上から編集できる様にする、最適な方法を調査する。

#### 調査内容

##### 1. ホーム画面に、アラーム設定の一覧を表示しておき、編集したい設定が編集された際に、アラーム編集画面を開く際のstartactivity時にパラーメーターとして渡せないか?

**Comment by nsaito92** [comment]
### 「2. アラーム設定画面にて、表示されてているデータを編集して、DBに保存できる様にする。」メモ

#### 必要な技術

* 必要な処理は、`SQLiteDatabase#update`。
    * [参考ページ](https://www.javadrive.jp/android/sqlite_data/index7.html)
* SQLiteDatabaseオブジェクトは、基本的に `SQLiteOpenHelper`クラスを継承したクラスから取得する。
    * [参考](https://tech.pjin.jp/blog/2013/02/23/sqliteopenhelper%E3%82%AF%E3%83%A9%E3%82%B9%E3%81%A8sqlitedatabase%E3%82%AF%E3%83%A9%E3%82%B9%E3%80%90android-tips%E3%80%91/)

#### 仕様について

* アラーム設定画面に、「保存」ボタンを追加する。
    * 現状の仕様だと、設定を一つ編集するごとにDBに書き込むことになり、DBを更新する頻度が高すぎる。
    * 「一つのアラーム設定」として、まとめてDBの更新ができる様な仕様で調整する。

**Comment by nsaito92** [comment]
```
@startuml


class AlarmPreferenceActivity {
    AlarmPreferenceFragment mFragment
    SwitchPreference alarmbutton
    Preference btn_alarmtime_key
    Preference btn_alarm_start_week_key
    Preference btn_alarm_setting_save
}

class FrockSettingsHelperController {
    FrockSettingsOpenHelper settingshelper
}

class FrockSettingsOpenHelper {

}

FrockSettingsHelperController --> FrockSettingsOpenHelper

@enduml
```

**Comment by nsaito92** [comment]
### 「3. TOP画面にて、DBのデータを元に現在のアラーム設定の一覧を表示できる様にする。」検討メモ

* テストで入れているデータを元に、トップ画面でリスト表示できる様にする。

#### やる事

* Androidのリスト表示の方法について調査
* 調査結果を元に実装

#### Androidのリスト表示について調査

* 以下でリスト表示に対応する。
* ListView
    * 縦にスクロールする一覧表示のための View。
    * ListView自体に、一覧の中身を管理する機能は無い。
    * Adapter という仕組みを用いて、データソースの管理と、データのViewへのバインドをさせる。
    * ListView は、スクロール位置に合わせて必要な View を Adapter から取り出す。
* SimpleCursorAdapter
    * Adapterの複数ある種類のうちの一つ。
    * データベースへ問い合わせた結果を View へ容易にバインドできるようにしたCursorAdapter。

##### 参考ページ

* [mixi-inc.github.io/AndroidTraining](http://mixi-inc.github.io/AndroidTraining/fundamentals/2.06.listView-and-viewPager.html)
* [sqliteで取得した値をListViewに表示する簡単な例
](https://qiita.com/zaburo/items/b02f439e3f2c5ddb1c58#helper)

**Comment by nsaito92** [comment]
実装範囲が広いので、別タスクを切って対応する。
